// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFRqf4wlynuP_qCagHHQiUEO7J6vlGmE',
    appId: '1:416417981791:web:4055b75aac98b4083242ea',
    messagingSenderId: '416417981791',
    projectId: 'eetha-37cb1',
    authDomain: 'eetha-37cb1.firebaseapp.com',
    storageBucket: 'eetha-37cb1.appspot.com',
    measurementId: 'G-83D04Z6HCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_jXdN0c3gxYB5YST5Ua8fXtBg85xzUk',
    appId: '1:416417981791:android:08b4cd84ae8d5e9e3242ea',
    messagingSenderId: '416417981791',
    projectId: 'eetha-37cb1',
    storageBucket: 'eetha-37cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn801rczjJIV_fHRBVOOoEDgwdihwH-n4',
    appId: '1:416417981791:ios:9e48993fbdd9024f3242ea',
    messagingSenderId: '416417981791',
    projectId: 'eetha-37cb1',
    storageBucket: 'eetha-37cb1.appspot.com',
    iosClientId: '416417981791-9ccrt31v9peualfvka2em1qu42s4rvg0.apps.googleusercontent.com',
    iosBundleId: 'com.darisi.eethaprm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn801rczjJIV_fHRBVOOoEDgwdihwH-n4',
    appId: '1:416417981791:ios:cce20d843885e5343242ea',
    messagingSenderId: '416417981791',
    projectId: 'eetha-37cb1',
    storageBucket: 'eetha-37cb1.appspot.com',
    iosClientId: '416417981791-b013ruc3dc0mb5f6no3fges90omgdtmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eethaprm',
  );
}
